azs:
- name: z1
  cloud_properties:
    zone: asia-southeast1-a
- name: z2
  cloud_properties:
    zone: asia-southeast1-b
- name: z3
  cloud_properties:
    zone: asia-southeast1-c

networks:
- name: default
  type: manual
  subnets:
  - range: ((internal_cidr))
    gateway: ((internal_gw))
    azs: [z1, z2, z3]
    dns: [8.8.8.8]
    static: ((static_ips))
    reserved: ((reserved_ips))
    cloud_properties:
      network_name: ((network))
      subnetwork_name: ((subnetwork))
      ephemeral_external_ip: true
      tags: ((tags))
- name: vip
  type: vip

vm_types:
- name: default
  cloud_properties:
    machine_type: n1-standard-2
    root_disk_size_gb: 20
    root_disk_type: pd-ssd
- name: small
  cloud_properties:
    machine_type: n1-standard-1
    root_disk_size_gb: 20
    root_disk_type: pd-ssd
- name: medium
  cloud_properties:
    machine_type: n1-standard-2
    root_disk_size_gb: 20
    root_disk_type: pd-ssd
- name: large
  cloud_properties:
    machine_type: n1-standard-4
    root_disk_size_gb: 20
    root_disk_type: pd-ssd
- name: large-disk50g
  cloud_properties:
    machine_type: n1-standard-4
    root_disk_size_gb: 50
    root_disk_type: pd-ssd
- name: large-disk100g
  cloud_properties:
    machine_type: n1-standard-4
    root_disk_size_gb: 100
    root_disk_type: pd-ssd
- name: large-disk500g
  cloud_properties:
    machine_type: n1-standard-4
    root_disk_size_gb: 500
    root_disk_type: pd-ssd
- name: cpu2-ram5
  cloud_properties:
    cpu: 2
    ram: 5
    root_disk_size_gb: 20
    root_disk_type: pd-ssd

disk_types:
- name: default
  disk_size: 10_000
- name: 10G
  disk_size: 10_000
- name: 20G
  disk_size: 20_000
- name: 30G
  disk_size: 30_000
- name: 50G
  disk_size: 50_000
- name: 100G
  disk_size: 100_000
- name: 500G
  disk_size: 500_000
  
compilation:
  workers: 4
  reuse_compilation_vms: true
  az: z1
  vm_type: default
  network: default
